CREATE TABLE ACTIVE_SESSIONS (
    id NUMBER PRIMARY KEY,
    user_id NUMBER NOT NULL,
    session_id VARCHAR2(100),
    current_page VARCHAR2(100),
    current_code CLOB,
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_coding NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE SESSION_SEQ START WITH 1 INCREMENT BY 1;
