CREATE TABLE TEACHER_MATERIALS (
    id NUMBER PRIMARY KEY,
    teacher_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    content CLOB,
    material_type VARCHAR2(50) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    class_date DATE,
    is_active NUMBER(1) DEFAULT 1,
    priority NUMBER DEFAULT 0
);

CREATE SEQUENCE TEACHER_MATERIAL_SEQ START WITH 1 INCREMENT BY 1;

-- StudyNote 테이블에 필드 추가
ALTER TABLE STUDY_NOTES ADD author_type VARCHAR2(20) DEFAULT 'STUDENT';
ALTER TABLE STUDY_NOTES ADD is_shared NUMBER(1) DEFAULT 0;
ALTER TABLE STUDY_NOTES ADD visibility VARCHAR2(20) DEFAULT 'PRIVATE';
ALTER TABLE STUDY_NOTES ADD parent_material_id NUMBER;
ALTER TABLE STUDY_NOTES ADD assignment_id NUMBER;
