spring:
  profiles:
    active: prod
  datasource:
    # Heroku는 DATABASE_URL 자동 사용, 로컬은 Oracle
    url: ${DATABASE_URL:jdbc:oracle:thin:@localhost:1521:XE}
    username: ${DB_USERNAME:javabattle}
    password: ${DB_PASSWORD:javabattle123}
    driver-class-name: ${DB_DRIVER:oracle.jdbc.OracleDriver}
  
  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.Oracle12cDialect}
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:defaultsecretkey}

anthropic:
  api:
    key: ${ANTHROPIC_API_KEY:your-default-key}
