spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: javabattle
    password: javabattle123
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
        
server:
  port: 8080
  
jwt:
  secret: javabattlearenasecretkeyforjwttoken2024verylongkeyforhs512algorithmsecurityrequirements
  expiration: 86400000