spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        
  profiles:
    active: prod
    
server:
  port: ${PORT:8080}
  
logging:
  level:
    org.springframework.security: INFO
    com.javabattle: INFO
    
jwt:
  secret: ${JWT_SECRET:java-battle-arena-super-secret-jwt-key-for-production-must-be-very-long-and-secure}
  expiration: 86400000
