spring:
  datasource:
    url: jdbc:postgresql://cduf3or326qj7m.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d65ek8v573fq4c
    username: u4bftv9a3g89dj
    password: p85e150befa9e4cf1f81ed85a6a6e46bb8e535a989cf136d3ffe0f851cce4ec30
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  thymeleaf:
    cache: false

server:
  port: 8080

jwt:
  secret: javabattlearenasecretkeyforjwttoken2024verylongkeyforhs512algorithmsecurityrequirements
  expiration: 86400000