spring:
  datasource:
    url: jdbc:oracle:thin:@adb.ap-chuncheon-1.oraclecloud.com:1522/gba75c561a7ea5d_javabattlearena_medium.adb.oraclecloud.com
    username: ADMIN
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
        
server:
  port: ${PORT:8080}
  
jwt:
  secret: ${JWT_SECRET:fallback-secret-key}
  expiration: 86400000

