spring:
  datasource:
    url: jdbc:oracle:thin:@adb.ap-chuncheon-1.oraclecloud.com:1522:javabattlearena
    username: ADMIN
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: false
        
server:
  port: ${PORT:8080}
  
jwt:
  secret: ${JWT_SECRET:fallback-secret-key}
  expiration: 86400000
