spring:
  datasource:
    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=gba75c561a7ea5d_javabattlearena_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ADMIN
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
        
server:
  port: ${PORT:8080}
  
jwt:
  secret: ${JWT_SECRET:fallback-secret-key}
  expiration: 86400000
