spring:
  datasource:
    url: jdbc:oracle:thin:@javabattlearena_medium?TNS_ADMIN=classpath:wallet
    username: ADMIN
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
        
server:
  port: ${PORT:8080}
  
jwt:
  secret: ${JWT_SECRET:fallback-secret-key}
  expiration: 86400000
