spring:
  profiles:
  datasource:
    url: ${DATABASE_URL:jdbc:oracle:thin:@localhost:1521:XE}
    username: ${DB_USERNAME:javabattle}
    password: ${DB_PASSWORD:javabattle123}
    driver-class-name: ${DB_DRIVER:oracle.jdbc.OracleDriver}
  
  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.Oracle12cDialect}
    hibernate:
      ddl-auto: update  # validate → update로 변경
    show-sql: false

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:defaultsecretkey}
  expiration: ${JWT_EXPIRATION:86400000}

anthropic:
  api:
    key: ${ANTHROPIC_API_KEY:your-default-key}