spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  thymeleaf:
    cache: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:fallback-secret-key}
  expiration: 86400000

claude:
  api:
    key: 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

logging:
  level:
    com.javabattle: INFO