spring:
  datasource:
    url: jdbc:oracle:thin:@adb.ap-chuncheon-1.oraclecloud.com:1522/gba75c561a7ea5d_javabattlearena_medium.adb.oraclecloud.com
    username: ADMIN
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  thymeleaf:
    cache: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:javabattlearenasecretkeyforjwttoken2024verylongkeyforhs512algorithmsecurityrequirements}
  expiration: 86400000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    oracle.jdbc: DEBUG
    com.javabattle.arena: DEBUG