spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: javabattle
    password: javabattle123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
  thymeleaf:
    cache: false

server:
  port: 8080

jwt:
  secret: javabattlearenasecretkeyforjwttoken2024verylongkeyforhs512algorithmsecurityrequirements
  expiration: 86400000
